### ISSUE TITLE
Create Fund Category

### ISSUE THREAD

**Issue by MiguelNery** [MiguelNery/Money#1]
App must create fund categories with a Category Name and initial Fund.

- [ ] Category Name can't be the same as one that already exist
- [ ] Category Name can't be empty
- [ ] Category Name does not differentiate by lower or upper case
- [ ] Initial Fund can have any positive value
